# Final Project Soccer Analysis
### Brian McCabe & Liam Pronovost

In [1]:
import pandas as pd
import numpy as np
import seaborn as sb

soccer = pd.read_csv("https://sports-statistics.com/database/soccer-data/england-premier-league-2005-to-2006.csv")
for i in range(2006,2020):
    soccer = soccer.loc[:,'Div':'AR']
    start = str(i)
    stop = str(i+1)
    link = "https://sports-statistics.com/database/soccer-data/england-premier-league-"+start+"-to-"+stop+".csv"
    print("Downloading data from ", link)
    df = pd.read_csv(link)
    df = df.loc[:,'Div':'AR']
    current = soccer
    soccer = pd.concat([current,df], axis=0)

soccer

Downloading data from  https://sports-statistics.com/database/soccer-data/england-premier-league-2006-to-2007.csv
Downloading data from  https://sports-statistics.com/database/soccer-data/england-premier-league-2007-to-2008.csv
Downloading data from  https://sports-statistics.com/database/soccer-data/england-premier-league-2008-to-2009.csv
Downloading data from  https://sports-statistics.com/database/soccer-data/england-premier-league-2009-to-2010.csv
Downloading data from  https://sports-statistics.com/database/soccer-data/england-premier-league-2010-to-2011.csv
Downloading data from  https://sports-statistics.com/database/soccer-data/england-premier-league-2011-to-2012.csv
Downloading data from  https://sports-statistics.com/database/soccer-data/england-premier-league-2012-to-2013.csv
Downloading data from  https://sports-statistics.com/database/soccer-data/england-premier-league-2013-to-2014.csv
Downloading data from  https://sports-statistics.com/database/soccer-data/england-premier-league-2014-to-2015.csv
Downloading data from  https://sports-statistics.com/database/soccer-data/england-premier-league-2015-to-2016.csv
Downloading data from  https://sports-statistics.com/database/soccer-data/england-premier-league-2016-to-2017.csv
Downloading data from  https://sports-statistics.com/database/soccer-data/england-premier-league-2017-to-2018.csv
Downloading data from  https://sports-statistics.com/database/soccer-data/england-premier-league-2018-to-2019.csv
Downloading data from  https://sports-statistics.com/database/soccer-data/england-premier-league-2019-to-2020.csv

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,AST,HF,AF,HC,AC,HY,AY,HR,AR,Time
0,E0,13/08/05,Aston Villa,Bolton,2.0,2.0,D,2.0,2.0,D,...,6.0,14.0,16.0,7.0,8.0,0.0,2.0,0.0,0.0,NaN
1,E0,13/08/05,Everton,Man United,0.0,2.0,A,0.0,1.0,A,...,5.0,15.0,14.0,8.0,6.0,3.0,1.0,0.0,0.0,NaN
2,E0,13/08/05,Fulham,Birmingham,0.0,0.0,D,0.0,0.0,D,...,4.0,12.0,13.0,6.0,6.0,1.0,2.0,0.0,0.0,NaN
3,E0,13/08/05,Man City,West Brom,0.0,0.0,D,0.0,0.0,D,...,3.0,13.0,11.0,3.0,6.0,2.0,3.0,0.0,0.0,NaN
4,E0,13/08/05,Middlesbrough,Liverpool,0.0,0.0,D,0.0,0.0,D,...,7.0,17.0,11.0,5.0,0.0,2.0,3.0,1.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,E0,01/01/2020,Watford,Wolves,2.0,1.0,H,1.0,0.0,H,...,4.0,12.0,6.0,4.0,7.0,3.0,1.0,1.0,0.0,15:00
204,E0,01/01/2020,Man City,Everton,2.0,1.0,H,0.0,0.0,D,...,2.0,11.0,11.0,3.0,6.0,0.0,4.0,0.0,0.0,17:30
205,E0,01/01/2020,Norwich,Crystal Palace,1.0,1.0,D,1.0,0.0,H,...,3.0,12.0,9.0,2.0,5.0,5.0,0.0,0.0,0.0,17:30
206,E0,01/01/2020,West Ham,Bournemouth,4.0,0.0,H,3.0,0.0,H,...,2.0,3.0,12.0,9.0,2.0,1.0,2.0,0.0,0.0,17:30
207,E0,01/01/2020,Arsenal,Man United,2.0,0.0,H,2.0,0.0,H,...,4.0,11.0,15.0,1.0,4.0,2.0,0.0,0.0,0.0,20:00

In [2]:
soccer.drop(['Time'], axis = 1, inplace = True)

In [3]:
print(soccer.isna().sum())

Div         1
Date        1
HomeTeam    1
AwayTeam    1
FTHG        1
FTAG        1
FTR         1
HTHG        1
HTAG        1
HTR         1
Referee     1
HS          1
AS          1
HST         1
AST         1
HF          1
AF          1
HC          1
AC          1
HY          1
AY          1
HR          1
AR          1
dtype: int64

In [4]:
soccer.dropna(inplace = True)
print(soccer.isna().sum())

Div         0
Date        0
HomeTeam    0
AwayTeam    0
FTHG        0
FTAG        0
FTR         0
HTHG        0
HTAG        0
HTR         0
Referee     0
HS          0
AS          0
HST         0
AST         0
HF          0
AF          0
HC          0
AC          0
HY          0
AY          0
HR          0
AR          0
dtype: int64